### ISSUE TITLE
deficiencies

### ISSUE THREAD

**Issue by binbontrr** [Nerimity/nerimity-web#104]
1-there is no push-to-talk button in the app (important)
2-no option to adjust contacts volume (important)
3-as visible on our profile; the link to our steam profile, our riot name, etc.
4-sound notification can be changed, current one is a bit annoying (or there may be an option to change)
5-I think servers with more than 1 or 2 members should be able to upload files.

**Comment by SupertigerDev** [comment]
I don't understand, what's wrong with 60 fps?

**Comment by binbontrr** [comment]
> I don't understand, what's wrong with 60 fps?
Sorry, I thought there was no 60fps option, I just saw it

**Comment by binbontrr** [comment]
+
4-sound notification can be changed, current one is a bit annoying

**Comment by SupertigerDev** [comment]
4. It can be changed. Can you please stop writing a false list?
