### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by ferucar** [Nerimity/nerimity-web#106]
hi guys. first of all great work so far!
I think that there should be an option for push-to-talk.
Also I wonder if we can use bots on nerimity or not.

**Comment by lexerotk** [comment]
![image](https://github.com/user-attachments/assets/c0a56bf1-0227-44a3-913c-52182e922d57)

Write here in Nerimity server.

**Comment by SupertigerDev** [comment]
> ![image](https://private-user-images.githubusercontent.com/80219527/378052860-c0a56bf1-0227-44a3-913c-52182e922d57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMjYyMTUsIm5iZiI6MTcyOTMyNTkxNSwicGF0aCI6Ii84MDIxOTUyNy8zNzgwNTI4NjAtYzBhNTZiZjEtMDIyNy00NGEzLTkxM2MtNTIxODJlOTIyZDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDA4MTgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZDg0MTAxYWUxOTBhYmYwNTE0ZTA3YmJlZTZiZDIwYWM0NGI1NjQ1NWNlZDE0MGRkMzQ4NjMyY2NkYmM3YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RKH9HT40BJxT0K-5T1h3I4zfcyGVrkrqlcVGYwYS77A)
> 
> Write here in Nerimity server.

no its better here, i prefer it in github, easier to track

**Comment by lexerotk** [comment]
> no its better here, i prefer it in github, easier to track

oh, i understand, sorry

**Comment by daveonHMD** [comment]
You can go here to create a bot

![image](https://github.com/user-attachments/assets/89584b18-84e0-4675-a511-a10549793e35) However, I'm not sure if there are any public bots available.

**Comment by bakapolice** [comment]
@SupertigerDev 
Do you planning to implement key bindings such as "Push to Mute" and "Push to Deafen" (with Deafen option) and some sound effects to mute/unmute micro and join/leave voice channel?

**Comment by SupertigerDev** [comment]
> @SupertigerDev 
> Do you planning to implement key bindings such as "Push to Mute" and "Push to Deafen" (with Deafen option) and some sound effects to mute/unmute micro and join/leave voice channel?

Maybe in the future

**Comment by SupertigerDev** [comment]
> You can go here to create a bot
> 
> ![image](https://github.com/user-attachments/assets/89584b18-84e0-4675-a511-a10549793e35) However, I'm not sure if there are any public bots available.
> 

There are public bots, you just have to find them
