### ISSUE TITLE
Turkish Translation For Nerimity

### ISSUE THREAD

**Issue by sutnax** [Nerimity/nerimity-web#11]
Hi, I want Turkish translation for nerimity. I already made a .json file already so the only thing will do is add it to nerimity.

[tr-TR.zip](https://github.com/Nerimity/nerimity-web/files/11688613/tr-TR.zip)
I hate GitHub, it couldn't make me send the .json file so i sent the zip file instead.

Thanks to SwappyFX for helping to do the translation.
https://github.com/SwappyFX

**Comment by SupertigerDev** [comment]
https://github.com/Nerimity/nerimity-web/commit/904d049e6fba91201927cf19660d54ffde2907cb

Thanks <3 Should be released in a couple of minutes.
