### ISSUE TITLE
I fixed some typos in the Turkish Translation.

### ISSUE THREAD

**Issue by sutnax** [Nerimity/nerimity-web#12]
I'm very sorry for typos in the translation. I hope theres no typo and i fixed it now.

[tr-TR.zip](https://github.com/Nerimity/nerimity-web/files/11689535/tr-TR.zip)

**Comment by sutnax** [comment]
A typo example:

![Screenshot_20230608-171009](https://github.com/Nerimity/nerimity-web/assets/68702247/b72031bf-56c9-4f8c-ae44-3c01634a38c0)

**Comment by SupertigerDev** [comment]
https://github.com/Nerimity/nerimity-web/commit/d9ccad70b2903361ad49eefdae00d0d239006e46

Thanks, should be updated when the next update comes out <3
