### ISSUE TITLE
Not letting me log in / create an a accont.

### ISSUE THREAD

**Issue by unhingedteabag** [Nerimity/nerimity-web#18]
![Screenshot 2023-06-30 6 45 28 PM](https://github.com/Nerimity/nerimity-web/assets/138262919/3505cb80-0bac-464f-af4c-58a183ba43cd)
i've been trying to log in for a a bit now and i've logged in before, the website stopped working when i tried to make a sever 
![Screenshot 2023-06-30 5 37 55 PM](https://github.com/Nerimity/nerimity-web/assets/138262919/cfb65365-3fbf-4b31-bd3f-dbd3ee2967d5)
^ that's what it showed.

and then none of my chats loaded. i logged out and i can't log in or make another account. 

(i also cleared my cache, + cookies and site data. not too sure if that also did something...?)

**Comment by SupertigerDev** [comment]
Sorry, the server crashed. It should be working again
