### ISSUE TITLE
Turkish Translation for New Features!

### ISSUE THREAD

**Issue by sutnax** [Nerimity/nerimity-web#20]
Hello, I was Inactive in Nerimity (sorry about that) and i didn't realise that new features were added. Now i translated the new features as well. Heres the .json file of it.
[tr-tr.zip](https://github.com/Nerimity/nerimity-web/files/11957756/tr-tr.zip)

**Comment by SupertigerDev** [comment]
Thanks! Will be added in the next release of nerimity.
