### ISSUE TITLE
Screensharing and webcam support

### ISSUE THREAD

**Issue by dillfrescott** [Nerimity/nerimity-web#22]
This would be awesome!

**Comment by Gersonzao** [comment]
Screen sharing already works.

**Comment by dillfrescott** [comment]
This issue was created before it was added

**Comment by SupertigerDev** [comment]
But webcam isn't added

**Comment by dillfrescott** [comment]
My bad

**Comment by christianlittle7** [comment]
Any idea on what timeline for webcam would be?
We're looking at Nerimity but for our use-case webcam support would be a big plus!

**Comment by SupertigerDev** [comment]
Hm interesting. It shouldn't be that hard to add, I'll try working on it today.

**Comment by SupertigerDev** [comment]
https://github.com/Nerimity/nerimity-web/commit/7f4001f5cf0fa2cd600dfc08f39e45591bd38fc4

Added webcam support
