### ISSUE TITLE
It's possible to view any messages (with permission or not) using the quote feature

### ISSUE THREAD

**Issue by dillfrescott** [Nerimity/nerimity-web#25]
You just need the id

**Comment by dillfrescott** [comment]
`[q:1398625960093458432]` this will load msg you weren't supposed to

**Comment by SupertigerDev** [comment]
Yes. I should probably make it so you can only quote messages if you are joined in that server or if it's in your DM channels :flushed:

**Comment by dillfrescott** [comment]
Yes I agree!
