### ISSUE TITLE
Nerimity crashes,, maybe a bug?

### ISSUE THREAD

**Issue by unhingedteabag** [Nerimity/nerimity-web#31]
Why has the app been crashing so much? and this one has been going on for hours...?

**Comment by SupertigerDev** [comment]
Because it only wants to crash when I'm sleeping, and I'm busy these days, so I don't work on nerimity as much

**Comment by SupertigerDev** [comment]
https://github.com/Nerimity/nerimity-server/commit/537e0c4404bb2177060389016a0cb02f111e093c
