### ISSUE TITLE
Message box autofocus

### ISSUE THREAD

**Issue by Gersonzao** [Nerimity/nerimity-web#44]
When you open a channel where you have permission to send messages, you have to focus the message box (either by clicking on it or tabbing to it) before you can type text into it. As suggested by another user of the client, a better option would be to leave it unfocused by default, but focus it when you start typing.

**Comment by billyisalive** [comment]
i think the nofications are nivce but if  you are afk ur compuer can  get i lil noisy

**Comment by billyisalive** [comment]
W RIZZ
