### ISSUE TITLE
Error 522 for long period of time

### ISSUE THREAD

**Issue by Neigdoig** [Nerimity/nerimity-web#72]
This morning, Nerimity was working, but when I tried to launch it multiple times on multiple devices, I get a 522 error. Is something going on with the Nerimity server?

**Comment by Gersonzao** [comment]
I think this better suits Discussions, but I can confirm that I'm also getting HTTP 522 since ~12 hours ago as of writing when trying to access the official instance.

**Comment by SupertigerDev** [comment]
Not sure whats going on 😭 course this happens midnight when im eeping 😔 I cant even ssh into the server or anything. MTR seems fine. i cant even contact my vps provider without doing their stupid troubleshooting question thing. and they ask for an mtr which is perfectly fine even though i cant connect. i cant even provide additional information.

**Comment by SupertigerDev** [comment]
Well, restarting the server fixed it, god knows what caused it to happen.
