### ISSUE TITLE
Wrong Chinese flag

### ISSUE THREAD

**Issue by 1enify** [Nerimity/nerimity-web#75]
After contacting a Traditional Chinese translator, he confirmed that the strings are in Traditional Chinese.
![image](https://github.com/Nerimity/nerimity-web/assets/135825033/18b95634-f628-4f75-95b7-8093ff173b3d)
Thus the flag should be changed from "🇨🇳" to "🇹🇼"

**Comment by SupertigerDev** [comment]
Thanks, fix will be live next time i create a new release.
