### ISSUE TITLE
Profile Picture Bug on iOS

### ISSUE THREAD

**Issue by Neigdoig** [Nerimity/nerimity-web#76]
As seen on the iOS version of Nerimity in Safari, when the profile picture of a certain user shows up, part of the screen is full of that yellow as a result of the profile picture not being fully contained, as shown below from user hala:
![2024-06-25_09-55](https://github.com/Nerimity/nerimity-web/assets/150962568/35b1b85e-563d-4925-af6c-7efeffc41278)

**Comment by SupertigerDev** [comment]
Move to android lol

**Comment by SupertigerDev** [comment]
Fr though, can't do anything about it. I don't have an iPhone :(

**Comment by Neigdoig** [comment]
Maybe I could test it, as I had mentioned before. Maybe once we get that done, you'll be able to move on to bigger and better things.

**Comment by SupertigerDev** [comment]
Nope. Probably won't get fixed unless I get an iPhone. I need to test myself. I don't even know what's causing this problem.

**Comment by SupertigerDev** [comment]
Fixed!
