### ISSUE TITLE
I cannot put gifs to my profile 

### ISSUE THREAD

**Issue by wyez2** [Nerimity/nerimity-web#96]
I download nerimity today it is mindblowing but I cant save my changes after putting gifs to my profile 

it says ''Saving...'' but never saves I tried other gifs but no it does not changes can you guys help?

**Comment by SupertigerDev** [comment]
Hello, could you show me the dev tools console by pressing the f12 key on your keyboard and then clicking the save changes button please

**Comment by SupertigerDev** [comment]
It could also take about 30 seconds or more to save

**Comment by wyez2** [comment]
> It could also take about 30 seconds or more to save

I took a shower and then come to check is it done and its still says ''Saving...''

**Comment by wyez2** [comment]
> Hello, could you show me the dev tools console by pressing the f12 key on your keyboard and then clicking the save changes button please

I am pressing f12 nothing happens

**Comment by SupertigerDev** [comment]
could you zip the image and send it to me somehow 🤔

**Comment by wyez2** [comment]
![github](https://github.com/user-attachments/assets/21fd80fc-c527-4fa3-8913-94fb98e964a6)

**Comment by wyez2** [comment]
![964mp8](https://github.com/user-attachments/assets/cb65a074-5a69-43d8-898d-10ebdf88dac2)
this was gif  I was trying to put

**Comment by wyez2** [comment]
![github2](https://github.com/user-attachments/assets/dad8b38f-54e5-4144-963d-98006374361d)
seven minutes after

**Comment by wyez2** [comment]
![github3](https://github.com/user-attachments/assets/37324702-f21e-4e66-ba31-282eef8a022b)
13 minutes after

**Comment by SupertigerDev** [comment]
Thanks, I have reproduced the problem, trying to find a fix

**Comment by wyez2** [comment]
no problem

**Comment by SupertigerDev** [comment]
Honestly, I've been trying for hours. It seems like it happens to big file size images. That gif is 6mb. Try a smaller gif for now. I still haven't found a solution yet ☹️

**Comment by SupertigerDev** [comment]
im gonna take a break

**Comment by wyez2** [comment]
I tried compress gif to 1.65 mb and problem continues

**Comment by blabla61** [comment]
Same promlem here. I also tried WEBP too, but I just cant put animated things to my avatar. I added a simple animated banner and it worked. maybe it can be about size, but why would you give us 12 mb space if you cant provide it?

**Comment by SupertigerDev** [comment]
fixed, it should work now after reloading.
